{% set name = "mcap" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/mcap-{{ version }}.tar.gz
  sha256: 9c385cc5e5a6bccff4aa0c6814b305faa2c3239ece46778661eaa6d809b1768a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - lz4
    - zstandard

test:
  imports:
    - mcap
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/foxglove/mcap
  summary: MCAP libraries for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
