{% set name = "mcap" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mcap-{{ version }}.tar.gz
  sha256: 5f0d5826ba3b8418508c1d992bada4c5744073f1b3e6d685579f0aca0389fb2f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - lz4
    - zstandard

test:
  imports:
    - mcap
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/foxglove/mcap
  summary: MCAP libraries for Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MilkClouds
